c("calc.ex")
{:ok, cfg} = Calc.futhark_context_config_new()
{:ok, ctx} = Calc.futhark_context_new(cfg)
{:ok, xs} = Calc.futhark_new_i64_1d(ctx, <<0, 0, 0, 0, 0, 0, 0, 1>>)
{:ok, ys} = Calc.futhark_new_i64_1d(ctx, <<0, 0, 0, 0, 0, 0, 0, 2>>)
{:ok, zs} = Calc.futhark_entry_add(ctx, xs, ys)
