c("calc.ex")
{:ok, cfg} = Calc.futhark_context_config_new()
{:ok, ctx} = Calc.futhark_context_new(cfg)
{:ok, xs} = Calc.futhark_new_i64_1d(ctx, <<1, 2, 3, 4>>)
{:ok, ys} = Calc.futhark_new_i64_1d(ctx, <<5, 6, 7, 8>>)
{:ok, zs} = Calc.futhark_entry_add(ctx, xs, ys)
